# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/hausd/Dateien/Xilinx_proj/hdmi_simple/hdmi_simple.srcs/sources_1/ip/clk_wiz_480p/clk_wiz_480p.xci
# IP: The module: 'clk_wiz_480p' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hausd/Dateien/Xilinx_proj/hdmi_simple/hdmi_simple.gen/sources_1/ip/clk_wiz_480p/clk_wiz_480p_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_480p'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/hausd/Dateien/Xilinx_proj/hdmi_simple/hdmi_simple.gen/sources_1/ip/clk_wiz_480p/clk_wiz_480p.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_480p'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/hausd/Dateien/Xilinx_proj/hdmi_simple/hdmi_simple.gen/sources_1/ip/clk_wiz_480p/clk_wiz_480p_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_480p'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/hausd/Dateien/Xilinx_proj/hdmi_simple/hdmi_simple.gen/sources_1/ip/clk_wiz_480p/clk_wiz_480p_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_480p'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/hausd/Dateien/Xilinx_proj/hdmi_simple/hdmi_simple.srcs/sources_1/ip/clk_wiz_480p/clk_wiz_480p.xci
# IP: The module: 'clk_wiz_480p' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hausd/Dateien/Xilinx_proj/hdmi_simple/hdmi_simple.gen/sources_1/ip/clk_wiz_480p/clk_wiz_480p_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_480p'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/hausd/Dateien/Xilinx_proj/hdmi_simple/hdmi_simple.gen/sources_1/ip/clk_wiz_480p/clk_wiz_480p.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_480p'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/hausd/Dateien/Xilinx_proj/hdmi_simple/hdmi_simple.gen/sources_1/ip/clk_wiz_480p/clk_wiz_480p_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_480p'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/hausd/Dateien/Xilinx_proj/hdmi_simple/hdmi_simple.gen/sources_1/ip/clk_wiz_480p/clk_wiz_480p_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_480p'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
